### PR TITLE
Speed limiter rework

### PR DESCRIPTION
**Pull request by fenugrec**
- existing speed limiter def : removed separate "km/h" template, instead
  use multiple scalings (SI / imp, selected within RR)
- add A2L based mVSPCT2,mVSPRC2 cut/restore limiter to templates

### CODE REVIEW

**Comment by fenugrec** [comment]
This one should be good to go ! I applied the change to all other roms currently in your repo.
Note, I found the locations in aq806 and 8u523 suspicious but I assume murph tested them back when he added them.

**Comment by mrphyslaw** [comment]
I believe those were both untested. If something seems suspicious it is probably likely wrong.

**Comment by ikabsd** [comment]
Tested on AM905/AM91A and it worked! Speed Limiter (stock) shows 180km/h and mVSPCT2 186km/h, that explains fenugrec findings are perfect!

**Review by a33b — APPROVED** [review]
The newly added mVSPCT2 and mVSPRC2 are fuel cut/restore. The "Speed Limiter" is throttle based.

**Pull request merged**
