### PR TITLE
New def : AM604

### PR DESCRIPTION
**Pull request by fenugrec**
Hey, I've started looking at bringing all our 3 repos more or less unified.

This adds an AM604 def, and also poses an interesting problem: either 5Y712 or 6Y300 have their "Intake Cam" map X/Y axis swapped. Not sure which is right, I haven't bothered simulating the code, but I'm sure one of them is wrong.

When you merge this, can you try "merge by rebasing" if you do it thru the github web UI, or "git merge --ff-only" if you're on the CLI. That should prevent the annoying merge commits everywhere.

PS you should be doing the same thing for your work branches : merge --ff-only, then delete workbranch. Keeps things nice, tidy and linear !

### CODE REVIEW

**Comment by a33b** [comment]
Before merging this, one of us needs to update the map names to suit the updated table_templates descriptions https://github.com/a33b/NissanDefs/commit/e02ce56e61f272d87f6ca4736702dcccc880c487
NISSAN_01 has also been changed to NISSAN_BASE for logger compatibility

**Comment by fenugrec** [comment]
will do, I forgot to check that. I see you've worked on the 5y712/6y300 axis situation, how did you determine which was right ?

**Comment by a33b** [comment]
> will do, I forgot to check that. I see you've worked on the 5y712/6y300 axis situation, how did you determine which was right ?

I did verify the axis orientation of 2D (I hate that RR calls them 3D) maps back when the A2L became available. It turned out ASAP2Demo was displaying them incorrectly. The 2D lookup routines with editable axis are very consistent; r4=map, r5=axis1 (Y), r6=axis2 (X), r7=axis1_input, stack_var=axis2_input
It's easiest to see with maps that have unequal axis, and map data that matches the correlation. As seen here; the torque values are the same from 0 to 800 RPM across the map. I doubt this map would govern at engine speeds this low and the data is probably just there as filler for a 16x16 map. Also, if the axis were reversed it doesn't make sense that the engine torque peaks at 6000 RPM, 3600 RPM is more accurate for a peak torque RPM.
image 019

Also note the large jump at the end of the vehicle speed axis and the consistent increase in the accelerator axis. The data in the map (whatever the units are ??) correlates better to these axis than if they were swapped 
image 018

**Comment by fenugrec** [comment]
> available. It turned out ASAP2Demo was displaying them incorrectly.

That's very odd, since it should just show whatever the A2L says...
I mostly agree with the generality of the r4-r7 + stack calling convention, but I have a faint, vague recollection of hitting one table that followed the opposite X/Y order, and I'm pretty sure I loaded it in HEW to simulate, but I completely forgot the result, forgot what table it was, and probably didn't take any notes. Dumbass.

I don't care as much now, but I think a good, simple way of verifying would be with live logging, watching the input and output values straight from RAM locations.

**Comment by fenugrec** [comment]
Fixed now. Sorry, should've tested it first before doing the PR !

**Comment by a33b** [comment]
I'd do it myself, but I don't think I have permissions;
change "Throttle Open" to "QH0/ torque conversion map" for those 2 maps and I believe the Fuel Target axis are reversed.

**Comment by fenugrec** [comment]
arg, missed those. wasn't getting any errors in RR though ?

Fuel target : yep missed that one too in the 5y712/300 mixup.

**Pull request merged**
